{% set name = "reportportal-client" %}
{% set version = "5.5.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b453e811dc7ed333ff0da5ea4ddc7aac752b8d5a5f3cc00411e767198e688bd4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - importlib-metadata
    - pip
    - python >=3.7
    - setuptools >=40.0
    - setuptools-scm
    - wheel
  run:
    - aenum
    - aiohttp >=3.8.3
    - certifi >=2023.7.22
    - python >=3.7
    - requests >=2.28.0

test:
  imports:
    - reportportal_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reportportal/client-Python
  summary: Python client for Report Portal v5.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
