{% set name = "reportportal-client" %}
{% set version = "5.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reportportal-client-{{ version }}.tar.gz
  sha256: 981003b3ab778aa9765e0b1ed92352f697e9e6c1188d8d11ebe988cc9a6d3040

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - importlib_metadata
    - pip
    - python >=3.7
    - setuptools >=40.0
    - setuptools-scm
  run:
    - aenum
    - aiohttp >=3.8.3
    - certifi >=2023.7.22
    - python >=3.7
    - requests >=2.28.0

test:
  source_files:
    - tests
  imports:
    - reportportal_client
  commands:
    - pip check
    # Test suite doesn't work because required files removed from sdist
    # - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/reportportal/client-Python
  summary: Python client for Report Portal v5.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
