{% set name = "reportportal-client" %}
{% set version = "5.6.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c927f745e3e4b9f1e146207adf9709651318fcf05e577ffdddb00998262704be

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - importlib-metadata
    - pip
    - python {{ python_min }}
    - setuptools >=40.0
    - setuptools-scm
    - wheel
  run:
    - python >={{ python_min }}
    - aenum
    - aiohttp >=3.10.11
    - certifi >=2024.8.30
    - requests >=2.32.3

test:
  imports:
    - reportportal_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/reportportal/client-Python
  summary: Python client for Report Portal v5.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
