{% set name = "reportportal-client" %}
{% set version = "5.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reportportal-client-{{ version }}.tar.gz
  sha256: 6339ad2c7745dcfcd4e4d204eb17a1f7595eabb63ee89785e645ed85823c1e23

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - importlib_metadata
    - pip
    - python >=3.6
    - setuptools >=40.0
    - setuptools-scm
  run:
    - aenum
    - delayed-assert
    - python >=3.6
    - requests >=2.23.0
    - six >=1.15.0

test:
  source_files:
    - tests
  imports:
    - reportportal_client
  commands:
    - pip check
    # Test suite doesn't work because required files removed from sdist
    # - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/reportportal/client-Python
  summary: Python client for Report Portal v5.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
