schema_version: 1

context:
  name: reportportal-client
  version: 5.6.7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 9010d947a023d19bf521f14a3a304872186bc82ec6e7cc9013ff6fcdd10ea0cf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - importlib-metadata
    - pip
    - setuptools >=40.0
    - setuptools-scm
    - wheel
    - importlib-metadata
  run:
    - python >=${{ python_min }}
    - aenum
    - typing-extensions >=4.13.2
    - requests >=2.32.3
    - aiohttp >=3.10.11
    - certifi >=2024.8.30

tests:
  - python:
      imports:
        - reportportal_client
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python client for Report Portal v5.
  license: Apache-2.0
  license_file: LICENSE.md
  homepage: https://github.com/reportportal/client-Python

extra:
  recipe-maintainers:
    - thewchan
